---
- name: Docker | Update all packages to their latest version. This might take a while
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: yes
  tags: docker

- name: Docker | Install required packages
  ansible.builtin.apt:
    pkg:
      - ca-certificates
      - gnupg
      - lsb-release
  tags: docker

- name: Docker | Add Docker's official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present
  tags: docker

- name: Docker | Add Docker stable repository
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_facts.lsb.codename }} stable
    filename: docker
    state: present
  tags: docker

- name: Docker | Install Docker Engine
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  tags: docker

- name: Docker | Add {{ docker_engine_user }} user on docker group
  ansible.builtin.user:
    name: "{{ docker_engine_user }}"
    groups: docker
    append: yes
  tags: docker

- name: Docker | Template a file to /etc/docker/daemon.json
  ansible.builtin.template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0640
  notify: Restart Docker
  tags: docker
